# Multiple Linear Regression Ordinary Least Squares Methodologies with Python

In [1]:
%reset
import pandas as pd
import numpy as np

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


# Matrix Math

In [29]:
X1 = (1,3,4,7,9,9)
X2 = (9,9,6,3,1,2)
Y = (3,5,6,8,7,10)

In [30]:
# Can either mean center the values or use the raw values
X1mean=np.mean(X1)
X2mean=np.mean(X2)
Ymean=np.mean(Y)

In [31]:
X1 = (1-X1mean,3-X1mean,4-X1mean,7-X1mean,9-X1mean,9-X1mean)
X2 = (9-X2mean,9-X2mean,6-X2mean,3-X2mean,1-X2mean,2-X2mean)
Y = (3-Ymean,5-Ymean,6-Ymean,8-Ymean,7-Ymean,10-Ymean)

In [32]:
X1=np.asarray(X1)
X1

array([-4.5, -2.5, -1.5,  1.5,  3.5,  3.5])

In [33]:
np.var(X2,ddof=1)

12.4

In [34]:
np.cov(X1,X2)

array([[ 11.1, -11.4],
       [-11.4,  12.4]])

In [35]:
np.cov(X1,Y)

array([[11.1,  7.3],
       [ 7.3,  5.9]])

In [36]:
np.cov(X2,Y)

array([[12.4, -7.2],
       [-7.2,  5.9]])

In [11]:
X2 = np.asarray(X2)
X2

array([ 4.,  4.,  1., -2., -4., -3.])

In [12]:
Y=np.asarray(Y)
Y

array([-3.5, -1.5, -0.5,  1.5,  0.5,  3.5])

In [13]:
X1.shape

(6,)

In [14]:
X_bias=np.ones((6,1)) # m is the number of records in the dataset
X_bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [15]:
X1=np.reshape(X1,(6,1))
X2=np.reshape(X2,(6,1))
Y=np.reshape(Y,(6,1))

In [16]:
X1

array([[-4.5],
       [-2.5],
       [-1.5],
       [ 1.5],
       [ 3.5],
       [ 3.5]])

In [17]:
Y

array([[-3.5],
       [-1.5],
       [-0.5],
       [ 1.5],
       [ 0.5],
       [ 3.5]])

In [18]:
newX=np.append(X_bias,X1,axis=1)
newX=np.append(newX,X2,axis=1)
newX

array([[ 1. , -4.5,  4. ],
       [ 1. , -2.5,  4. ],
       [ 1. , -1.5,  1. ],
       [ 1. ,  1.5, -2. ],
       [ 1. ,  3.5, -4. ],
       [ 1. ,  3.5, -3. ]])

In [19]:
newX.shape

(6, 3)

In [20]:
X_transpose=np.transpose(newX)
X_transpose

array([[ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [-4.5, -2.5, -1.5,  1.5,  3.5,  3.5],
       [ 4. ,  4. ,  1. , -2. , -4. , -3. ]])

In [21]:
X_transpose.shape

(3, 6)

In [22]:
XtX=((X_transpose.dot(newX)))
XtX

array([[  6. ,   0. ,   0. ],
       [  0. ,  55.5, -57. ],
       [  0. , -57. ,  62. ]])

In [23]:
XtX_Inverse=np.linalg.inv(XtX)
XtX_Inverse

array([[ 0.16666667,  0.        ,  0.        ],
       [-0.        ,  0.32291667,  0.296875  ],
       [ 0.        ,  0.296875  ,  0.2890625 ]])

In [24]:
Y

array([[-3.5],
       [-1.5],
       [-0.5],
       [ 1.5],
       [ 0.5],
       [ 3.5]])

In [25]:
X_transpose

array([[ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [-4.5, -2.5, -1.5,  1.5,  3.5,  3.5],
       [ 4. ,  4. ,  1. , -2. , -4. , -3. ]])

In [26]:
XtY=((X_transpose.dot(Y)))
XtY

array([[  0. ],
       [ 36.5],
       [-36. ]])

In [27]:
XtX_Inverse.dot(XtY)

array([[0.        ],
       [1.09895833],
       [0.4296875 ]])

In [44]:
X1 = (1,3,4,7,9,9)
X2 = (9,9,6,3,1,2)
Y = (3,5,6,8,7,10)

In [38]:
# Can either mean center the values or use the raw values
X1mean=np.mean(X1)
X2mean=np.mean(X2)
Ymean=np.mean(Y)

In [39]:
X1 = (1-X1mean,3-X1mean,4-X1mean,7-X1mean,9-X1mean,9-X1mean)
X2 = (9-X2mean,9-X2mean,6-X2mean,3-X2mean,1-X2mean,2-X2mean)
Y = (3-Ymean,5-Ymean,6-Ymean,8-Ymean,7-Ymean,10-Ymean)

In [45]:
X1=np.asarray(X1)
X2=np.asarray(X2)
Y=np.asarray(Y)

In [46]:
X1=np.reshape(X1,(6,1))
X2=np.reshape(X2,(6,1))
Y=np.reshape(Y,(6,1))

In [47]:
df=np.append(X1,X2,axis=1)
df=np.append(df,Y,axis=1)
df=pd.DataFrame(df,columns=["X1","X2","Y"])
df

X1  X2   Y
0   1   9   3
1   3   9   5
2   4   6   6
3   7   3   8
4   9   1   7
5   9   2  10

In [48]:
from statsmodels.formula.api import ols

model1=ols('Y~X1+X2',data=df)
results1=model1.fit()
print(results1.summary2())

                Results: Ordinary least squares
Model:              OLS              Adj. R-squared:     0.726  
Dependent Variable: Y                AIC:                21.7589
Date:               2022-11-08 11:20 BIC:                21.1342
No. Observations:   6                Log-Likelihood:     -7.8795
Df Model:           2                F-statistic:        7.611  
Df Residuals:       3                Prob (F-statistic): 0.0668 
R-squared:          0.835            Scale:              1.6189 
-----------------------------------------------------------------
             Coef.   Std.Err.     t     P>|t|    [0.025    0.975]
-----------------------------------------------------------------
Intercept   -1.6927    7.3632  -0.2299  0.8330  -25.1258  21.7404
X1           1.0990    0.7230   1.5199  0.2259   -1.2021   3.4000
X2           0.4297    0.6841   0.6281  0.5745   -1.7474   2.6067
----------------------------------------------------------------
Omnibus:              nan          D

C:\Users\carol\anaconda3\lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
