# Simple Linear Regression Ordinary Least Squares Methodologies with Python

In [2]:
%reset
import pandas as pd
import numpy as np

Once deleted, variables cannot be recovered. Proceed (y/[n])?  y


# Matrix Math

In [29]:
X=(4,4.5,5,5.5,6,6.5,7)
Y = (33,42,45,51,53,61,62)
meanY=np.mean(Y)
Ymc=(Y-meanY)
Xmc=(X-np.mean(X))

In [30]:
# Can either mean center the values or use the raw values
#X = (-1.5,-1,-.5,0,.5,1,1.5)
#Y = (-16.6,-7.6,-4.6,1.4,3.4,11.4,12.4)

In [31]:
np.var(Ymc,ddof=1)

108.61904761904763

In [32]:
X_biasA=np.ones((1,7))
X_biasA
np.cov(X_biasA,Xmc)

array([[0.        , 0.        ],
       [0.        , 1.16666667]])

In [33]:
np.cov(Xmc,Ymc)

array([[  1.16666667,  11.08333333],
       [ 11.08333333, 108.61904762]])

In [34]:
Xmc=np.asarray(Xmc)
Xmc

array([-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5])

In [35]:
sum(Ymc)

1.4210854715202004e-14

In [36]:
Ymc=np.asarray(Ymc)

In [37]:
Xmc.shape

(7,)

In [38]:
X_bias=np.ones((7,1)) # m is the number of records in the dataset
X_bias

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [39]:
Xmc=np.reshape(Xmc,(7,1))
Ymc=np.reshape(Ymc,(7,1))

In [40]:
Xmc

array([[-1.5],
       [-1. ],
       [-0.5],
       [ 0. ],
       [ 0.5],
       [ 1. ],
       [ 1.5]])

In [41]:
np.transpose(Xmc)

array([[-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5]])

In [42]:
XtXA=((np.transpose(Xmc).dot(Xmc)))
XtXA

array([[7.]])

the sum of the squares (the deviations from the mean)

In [44]:
Ymc

array([[-16.57142857],
       [ -7.57142857],
       [ -4.57142857],
       [  1.42857143],
       [  3.42857143],
       [ 11.42857143],
       [ 12.42857143]])

In [46]:
newX=np.append(X_bias,Xmc,axis=1)
newX

array([[ 1. , -1.5],
       [ 1. , -1. ],
       [ 1. , -0.5],
       [ 1. ,  0. ],
       [ 1. ,  0.5],
       [ 1. ,  1. ],
       [ 1. ,  1.5]])

In [47]:
newX.shape

(7, 2)

In [48]:
X_transpose=np.transpose(newX)
X_transpose

array([[ 1. ,  1. ,  1. ,  1. ,  1. ,  1. ,  1. ],
       [-1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5]])

In [49]:
X_transpose.shape

(2, 7)

In [58]:
XtX=((X_transpose.dot(newX)))
XtX

array([[7., 0.],
       [0., 7.]])

In [59]:
XtX_Inverse=np.linalg.inv(XtX)
XtX_Inverse

array([[0.14285714, 0.        ],
       [0.        , 0.14285714]])

In [60]:
XtYmc=((X_transpose.dot(Ymc)))
XtYmc

array([[1.42108547e-14],
       [6.65000000e+01]])

In [62]:
XtX_Inverse.dot(XtYmc)

array([[2.0301221e-15],
       [9.5000000e+00]])

To recover the y-intercept use the formula y_mean = a + b1 * x_mean 

In [76]:
y_intercept=np.mean(Y) - 9.5 * np.mean(X)
y_intercept

-2.6785714285714306

can check with python

In [69]:
XA = (4,4.5,5,5.5,6,6.5,7)
YA = (33,42,45,51,53,61,62)

In [70]:
XA=np.asarray(XA)
YA=np.asarray(YA)

In [71]:
XA=np.reshape(XA,(7,1))
YA=np.reshape(YA,(7,1))

In [73]:
df=np.append(XA,YA,axis=1)
df=pd.DataFrame(df,columns=["XA","YA"])
df

XA    YA
0  4.0  33.0
1  4.5  42.0
2  5.0  45.0
3  5.5  51.0
4  6.0  53.0
5  6.5  61.0
6  7.0  62.0

In [74]:
from statsmodels.formula.api import ols

model1=ols('YA~XA',data=df)
results1=model1.fit()
print(results1.summary2())

                 Results: Ordinary least squares
Model:              OLS              Adj. R-squared:     0.963   
Dependent Variable: YA               AIC:                31.2014 
Date:               2022-11-09 14:58 BIC:                31.0932 
No. Observations:   7                Log-Likelihood:     -13.601 
Df Model:           1                F-statistic:        158.2   
Df Residuals:       5                Prob (F-statistic): 5.64e-05
R-squared:          0.969            Scale:              3.9929  
------------------------------------------------------------------
              Coef.   Std.Err.     t     P>|t|    [0.025    0.975]
------------------------------------------------------------------
Intercept    -2.6786    4.2220  -0.6344  0.5537  -13.5316   8.1744
XA            9.5000    0.7553  12.5786  0.0001    7.5586  11.4414
-----------------------------------------------------------------
Omnibus:               nan          Durbin-Watson:          2.749
Prob(Omnibus):        

C:\Users\carol\anaconda3\lib\site-packages\statsmodels\stats\stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 7 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
